openapi: 3.0.0
info:
  title: ParkC; - Parking Lot API
  version: 1.0.0
  description: API for managing parking lots

paths:
  /api/get_lots:
    get:
      summary: Get all parking lots
      responses:
        '200':
          description: A list of all parking lots

  /api/add_lot:
    post:
      summary: Add a new parking lot and its spots automatically
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prime_location_name:
                  type: string
                price:
                  type: number
                address:
                  type: string
                pin_code:
                  type: string
                maximum_number_of_spots:
                  type: integer
      responses:
        '201':
          description: New lot created with spots

  /api/edit_lot/{id}:
    put:
      summary: Updating an existing parking lot
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prime_location_name:
                  type: string
                price:
                  type: number
                address:
                  type: string
                pin_code:
                  type: string
                maximum_number_of_spots:
                  type: integer
      responses:
        '200':
          description: Lot updated
        '404':
          description: Lot not found

  /api/delete_lot/{id}:
    delete:
      summary: Deletes a parking lot
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lot deleted
        '404':
          description: Lot id not found

  /api/search_lot/{id}:
    get:
      summary: Search parking lot by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '404':
          description: Lot not found
